apiVersion: apps/v1
kind: Deployment
metadata:
  name: noders
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      name: nodeapp
      labels:
        app: node
    spec:
      imagePullSecrets:
      - name: dockerhublogin
      containers:
      - name: nodeapp
        image: mylandmarktech/nodejs-fe-app
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9981

---
apiVersion: v1
kind: Service
metadata:
  name: nodesvc
spec:
  type: NodePort
  selector:
    app: node
  ports:
  - port: 80
    targetPort: 9981
    nodePort: 31500

