apiVersion: v1
kind: Service
metadata:
  name: appsvc
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
  - port:  80
    targetPort: 5000
    nodePort: 31200

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

